#!/bin/bash

subdir="cli"

if [[ "$1" == "build" ]]; then
  cd "$subdir"
  go build
  echo "Built cli program. Type /run <replace with inputFile.txt> to run"
elif [[ "$1" == "install" ]]; then
  cd "$subdir"
  go install
  echo "Installed all dependencies"
elif [[ "$1" == "test" ]]; then
  cd "$subdir"
  echo "running tests"
  go test ./metrics/ -cover -v > tests.out
  run=`grep -c RUN tests.out`
  passed=`grep -c PASS: tests.out`
  coverage=`grep -e % tests.out`
  echo "$run/$passed tests passed"
  echo ${coverage:0:29}
elif [[ -n "$1" ]]; then
  cli/cli "$1"
fi
